services:
  redis_server_ai:
    image: redis:alpine
    container_name: redis_server_ai
    ports: ["6379:6379"] 
    networks:
      - violence-detection-net

  viomobilenet_api:
    build: .
    image: viomobilenet-system
    container_name: viomobilenet_api
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    volumes:
      - ./uploads:/app/uploads
    environment:
      - S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=mypassword
      - S3_BUCKET_NAME=inference-results
    depends_on:
      - redis_server_ai
    networks:
      - violence-detection-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        # limits:
        #   memory: 2G # Ép API không được ăn quá 2GB
        #   cpus: '1.0' # Giới hạn tổng CPU cho API

  viomobilenet_worker:
    build: .
    image: viomobilenet-system
    container_name: viomobilenet_worker
    command: celery -A worker.celery_app worker --loglevel=info --pool=solo
    volumes:
      - ./uploads:/app/uploads
    environment:
      - S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - redis_server_ai
    networks:
      - violence-detection-net
    deploy:
      resources:
        limits:
          cpus: '1.0'  
          memory: 2G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


networks:
  violence-detection-net:
    name: violence-detection-net 
    external: true 
volumes: {}