###############################################
# CẤU HÌNH MEDIA MTX (CHO VPS 103.78.3.29)
###############################################
paths:
  all:
    source: publisher

# LOGGING
logLevel: info

# RTSP (Input)
rtsp: yes
rtspAddress: :8554

# RTMP (Disable cho nhẹ)
rtmp: no

# HLS (Output)
hls: yes
hlsAddress: :8888
hlsSegmentCount: 5
hlsSegmentDuration: 1s

# WebRTC (Output - QUAN TRỌNG)
webrtc: yes
webrtcAddress: :8889
webrtcAllowOrigin: '*'
# QUAN TRỌNG: Khai báo IP VPS để client biết đường kết nối UDP
webrtcICECandidates:
  - "103.78.3.29:8189"
webrtcUDPAddress: :8189
